# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170228_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Board'),
        ),
    ]
